"""
build_windows_exe.py — PyInstaller packaging script
=====================================================
Run this on a Windows machine with PyInstaller installed to produce
a self-contained .exe that requires no Python installation.

    python build_windows_exe.py

Output: release/FilamentWindingCAM.exe  (one-file bundle, ~80 MB)

Requirements (run install_deps_windows.bat first, then):
    pip install pyinstaller

The resulting exe contains all Python code and Qt DLLs. End users do not
need Python, pip, or any packages installed.
"""
from __future__ import annotations
import subprocess, sys, shutil, os
from pathlib import Path

ROOT    = Path(__file__).resolve().parent
RELEASE = ROOT / 'release'
DIST    = ROOT / 'dist'
BUILD   = ROOT / 'build_pyinstaller'
SPEC    = ROOT / 'FilamentWindingCAM.spec'

# ─── 0. Verify PyInstaller ──────────────────────────────────────────────────
try:
    import PyInstaller
except ImportError:
    print("PyInstaller not found. Installing…")
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'pyinstaller'])

# ─── 1. Build spec content ──────────────────────────────────────────────────
# Data files: include all Python source packages as-is so that importlib
# can locate real_esp32_link.py at the expected relative path.
spec_content = """\
# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by build_windows_exe.py — do not edit by hand.

import sys
from pathlib import Path
ROOT = Path(SPECPATH)

block_cipher = None

a = Analysis(
    [str(ROOT / 'app_launcher.py')],
    pathex=[str(ROOT)],
    binaries=[],
    datas=[
        (str(ROOT / 'faz17_d1' / 'faz17_d1_backend'), 'faz17_d1/faz17_d1_backend'),
        (str(ROOT / 'faz17_d2' / 'faz17_d2_app' / 'faz17_d2'), 'faz17_d2/faz17_d2_app/faz17_d2'),
        (str(ROOT / 'faz18_bringup' / 'real_esp32_link.py'), 'faz18_bringup'),
    ],
    hiddenimports=[
        'PySide6.QtOpenGL',
        'PySide6.QtOpenGLWidgets',
        'pyqtgraph',
        'pyqtgraph.graphicsItems.PlotDataItem',
        'numpy',
        'OpenGL',
        'serial',
        'sqlite3',
        'faz17_d1',
        'faz17_d1.hardware',
        'faz17_d1.hardware.esp32_link',
        'faz17_d1.hardware.telemetry_stream',
        'faz17_d1.hardware.can_bus',
        'faz17_d1.core',
        'faz17_d1.core.safety_controller',
        'faz17_d1.core.motion_controller',
        'faz17_d1.core.digital_twin',
        'faz17_d1.core.winding_planner',
        'faz17_d1.ai',
        'faz17_d1.ai.predictive_maintenance',
        'faz17_d1.persistence',
        'faz17_d1.persistence.recipe_db',
        'faz17_d1.persistence.telemetry_db',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='FilamentWindingCAM',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,          # no console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # icon='assets/icon.ico',  # uncomment if you have an .ico
)
"""

# ─── 2. Write spec ──────────────────────────────────────────────────────────
SPEC.write_text(spec_content, encoding='utf-8')
print(f"Wrote spec: {SPEC}")

# ─── 3. Run PyInstaller ─────────────────────────────────────────────────────
cmd = [
    sys.executable, '-m', 'PyInstaller',
    '--clean',
    '--noconfirm',
    f'--distpath={DIST}',
    f'--workpath={BUILD}',
    str(SPEC),
]
print(f"\nRunning: {' '.join(cmd)}\n")
result = subprocess.run(cmd, cwd=str(ROOT))

if result.returncode != 0:
    print("\nPyInstaller failed. Common fixes:")
    print("  - pip install pyinstaller --upgrade")
    print("  - Run as Administrator if permission errors occur")
    print("  - Check all imports succeed: python app_launcher.py")
    sys.exit(result.returncode)

# ─── 4. Move to release/ ────────────────────────────────────────────────────
RELEASE.mkdir(exist_ok=True)
src = DIST / 'FilamentWindingCAM.exe'
dst = RELEASE / 'FilamentWindingCAM.exe'

if src.exists():
    shutil.move(str(src), str(dst))
    size_mb = dst.stat().st_size / 1_048_576
    print(f"\n{'='*60}")
    print(f"  BUILD SUCCESSFUL")
    print(f"  Output: {dst}")
    print(f"  Size:   {size_mb:.1f} MB")
    print(f"{'='*60}")
    print("\nTo distribute: copy release/FilamentWindingCAM.exe to the target machine.")
    print("No Python installation required on end-user machines.")
else:
    print(f"\nWARNING: Expected output not found at {src}")
    print(f"Check {DIST}/ for build artefacts.")
    sys.exit(1)
